site_name: Tester
site_description: A flexible Python tool for automating UVM testbench execution
repo_url: https://github.com/yourusername/tester
site_author: Your Name

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - footnotes
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Overview: user-guide/overview.md
    - Build Systems: user-guide/build-systems.md
    - Simulators: user-guide/simulators.md
    - Test Management: user-guide/test-management.md
    - Command Line Interface: user-guide/cli.md
  - Reference:
    - Configuration File: reference/configuration-file.md
    - Makefile Integration: reference/makefile-integration.md
    - Example Configurations: reference/example-configurations.md
  - Development:
    - Architecture: development/architecture.md
    - Contributing: development/contributing.md
    - Roadmap: development/roadmap.md
  - CI/CD: ci-cd.md